name: linting-wf
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install HTMLHint
        run: npm install --save-dev htmlhint
      - name: Install stylelint 
        run: npm install --save-dev stylelint   # Fixed the typo here
      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"   # Corrected the pattern to match HTML files properly
      - name: Lint CSS Files
        run: npx stylelint "**/*.css"   # Corrected the pattern to match CSS files properly
      - name: Display package.json Contents
        run: cat package.json